name: deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "releasetr-/**" ]


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: "curl --request POST -A \"${{ secrets.USER_AGENT }}\" --header \"PRIVATE-TOKEN: ${{ secrets.GL_TOKEN }} \" \"${{ secrets.HOST_NAME }}/api/v4/projects/${{ secrets.PROJECT }}/pipeline?ref=${{ secrets.BRANCH }}\" -L"


#test!!!!
#hello world
